.PHONY: all clean

all:
	$(MAKE) -C SYSTEM-V/client
	$(MAKE) -C SYSTEM-V/server
	$(MAKE) -C POSIX/client
	$(MAKE) -C POSIX/server

clean:
	$(MAKE) -C SYSTEM-V/client clean
	$(MAKE) -C SYSTEM-V/server clean
	$(MAKE) -C POSIX/client clean
	$(MAKE) -C POSIX/server clean
